"use client";

import * as React from "react";
import { Briefcase, CheckCircle2, Clock, Shield, Users, Wallet, Zap } from "lucide-react";
import type { MemberEarningsSummary, RevenueDeal } from "@/lib/db/earnings";

function money(value: number, currency = "PKR") {
  return new Intl.NumberFormat("en-PK", { style: "currency", currency, maximumFractionDigits: 0 }).format(value);
}

function Stat({ label, value, detail, icon: Icon, color = "#24C5E3" }: { label: string; value: string; detail: string; icon: typeof Briefcase; color?: string }) {
  return <div className="rounded-2xl border border-white/[0.08] bg-[#0E1117]/90 p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-wider text-[#6B7280]">{label}</span><Icon className="size-4" style={{ color }} /></div><p className="mt-3 text-2xl font-black text-[#F5F7FA]">{value}</p><p className="mt-1 text-[11px] text-[#6B7280]">{detail}</p></div>;
}

function DealRow({ deal }: { deal: RevenueDeal }) {
  const commission = deal.commission_entries.reduce((sum, entry) => sum + entry.amount, 0);
  const companyShare = Math.max(0, deal.amount_paid - commission);
  return <article className="rounded-2xl border border-white/[0.08] bg-[#0E1117]/85 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-bold text-[#F5F7FA]">{deal.project?.name ?? "Project"}</p><p className="mt-1 text-xs text-[#6B7280]">Paid revenue · {new Date(deal.created_at).toLocaleDateString()}</p></div><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ${deal.payment_status === "paid" ? "bg-[#39FF14]/10 text-[#39FF14]" : "bg-[#F5B942]/10 text-[#F5B942]"}`}>{deal.payment_status.replace("_", " ")}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><div><p className="text-[#6B7280]">Paid amount</p><p className="mt-1 font-bold text-[#F5F7FA]">{money(deal.amount_paid, deal.currency)}</p></div><div><p className="text-[#6B7280]">My commission</p><p className="mt-1 font-bold text-[#39FF14]">{money(commission, deal.currency)}</p></div><div><p className="text-[#6B7280]">Company share</p><p className="mt-1 font-bold text-[#A7AFBC]">{money(companyShare, deal.currency)}</p></div><div><p className="text-[#6B7280]">Payout</p><p className="mt-1 font-bold text-[#A7AFBC]">{deal.commission_entries.every((entry) => entry.status === "paid") ? "Paid" : "Pending"}</p></div></div></article>;
}

export function MemberEarningsPanel({ summary }: { summary: MemberEarningsSummary }) {
  const [current, setCurrent] = React.useState(summary);
  const refresh = async () => { const response = await fetch("/api/earnings/summary", { cache: "no-store" }); if (response.ok) setCurrent(await response.json() as MemberEarningsSummary); };
  const name = current.employee?.full_name || current.employee?.email || "Member";
  return <div className="space-y-6"><div className="rounded-2xl border border-[#39FF14]/20 bg-gradient-to-br from-[#0E1117] to-[#111C12] p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-[#39FF14]"><Wallet className="size-3.5" /> Noryxa Partner Network</div><h1 className="mt-2 text-3xl font-black text-[#F5F7FA]">My Earnings</h1><p className="mt-1 text-sm text-[#A7AFBC]">Welcome, {name}. Track your real paid-project commission and direct mentor earnings.</p></div><button type="button" onClick={() => void refresh()} className="w-fit rounded-xl border border-white/10 px-3 py-2 text-xs font-semibold text-[#A7AFBC] hover:bg-white/5 hover:text-white">Refresh ledger</button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Total commission" value={money(current.myCommission)} detail="Closer + direct sponsor" icon={Wallet} color="#39FF14" /><Stat label="Pending commission" value={money(current.pendingCommission)} detail="Awaiting admin payout" icon={Clock} color="#F5B942" /><Stat label="Paid commission" value={money(current.paidCommission)} detail="Marked paid by company" icon={CheckCircle2} color="#24C5E3" /><Stat label="This month" value={money(current.monthlyEarnings)} detail="Current month earnings" icon={Zap} color="#8B5CF6" /></div>
    <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border border-white/[0.08] bg-[#0E1117]/90 p-5"><div className="flex items-center gap-2"><Briefcase className="size-4 text-[#24C5E3]" /><h2 className="text-sm font-bold text-[#F5F7FA]">My Sales</h2></div><div className="mt-5 grid grid-cols-2 gap-4"><div><p className="text-xs text-[#6B7280]">Clients generated</p><p className="mt-1 text-2xl font-black text-[#F5F7FA]">{current.clientsGenerated}</p></div><div><p className="text-xs text-[#6B7280]">Deals closed</p><p className="mt-1 text-2xl font-black text-[#F5F7FA]">{current.dealsClosed}</p></div><div><p className="text-xs text-[#6B7280]">Personal sales</p><p className="mt-1 text-lg font-bold text-[#39FF14]">{money(current.personalSales)}</p></div><div><p className="text-xs text-[#6B7280]">Direct commission</p><p className="mt-1 text-lg font-bold text-[#A7AFBC]">{money(current.myCommission - current.referralEarnings)}</p></div></div></section><section className="rounded-2xl border border-white/[0.08] bg-[#0E1117]/90 p-5"><div className="flex items-center gap-2"><Users className="size-4 text-[#8B5CF6]" /><h2 className="text-sm font-bold text-[#F5F7FA]">My Network</h2></div><div className="mt-5 grid grid-cols-2 gap-4"><div><p className="text-xs text-[#6B7280]">Direct members</p><p className="mt-1 text-2xl font-black text-[#F5F7FA]">{current.directMembers}</p></div><div><p className="text-xs text-[#6B7280]">Active members</p><p className="mt-1 text-2xl font-black text-[#39FF14]">{current.activeMembers}</p></div><div><p className="text-xs text-[#6B7280]">Their paid projects</p><p className="mt-1 text-lg font-bold text-[#F5F7FA]">{current.theirProjects}</p></div><div><p className="text-xs text-[#6B7280]">Referral earnings</p><p className="mt-1 text-lg font-bold text-[#8B5CF6]">{money(current.referralEarnings)}</p></div></div></section></div>
    <section className="rounded-2xl border border-[#24C5E3]/15 bg-[#0E1117]/90 p-5"><div className="flex items-center gap-2"><Shield className="size-4 text-[#24C5E3]" /><div><h2 className="text-sm font-bold text-[#F5F7FA]">Protected revenue model</h2><p className="mt-1 text-xs text-[#6B7280]">Company share remains protected. Commission is created only after a client payment is recorded.</p></div></div></section>
    <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-sm font-bold uppercase tracking-wider text-[#A7AFBC]">My paid deals</h2><span className="text-xs text-[#6B7280]">{current.deals.length} visible</span></div>{current.deals.length === 0 ? <div className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-sm text-[#6B7280]">Your paid project commissions will appear here.</div> : current.deals.map((deal) => <DealRow key={deal.id} deal={deal} />)}</section>
    <section className="space-y-3"><h2 className="text-sm font-bold uppercase tracking-wider text-[#A7AFBC]">Direct members</h2>{current.directMemberRows.length === 0 ? <div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-[#6B7280]">No direct members assigned yet.</div> : <div className="grid gap-3 sm:grid-cols-2">{current.directMemberRows.map((member) => <div key={member.id} className="flex items-center justify-between rounded-xl border border-white/[0.08] bg-[#0E1117]/80 px-4 py-3"><div><p className="text-sm font-semibold text-[#F5F7FA]">{member.full_name || member.email}</p><p className="text-[11px] text-[#6B7280]">{member.job_title || "Noryxa partner"}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${member.employment_status === "active" ? "bg-[#39FF14]/10 text-[#39FF14]" : "bg-white/5 text-[#6B7280]"}`}>{member.employment_status}</span></div>)}</div>}</section>
  </div>;
}
