-- 20260906000000_storage_buckets_and_policies.sql
-- Add storage buckets for various file types and corresponding RLS policies.

-- Storage buckets are rows in Supabase's managed storage.buckets table.
-- Keep the existing hyphenated IDs from the initial migration and add the
-- document-specific buckets used by the file-management APIs.
insert into storage.buckets (id, name, public) values
  ('avatars', 'avatars', false),
  ('task-attachments', 'task-attachments', false),
  ('daily-report-attachments', 'daily-report-attachments', false),
  ('documents', 'documents', false),
  ('employee-documents', 'employee-documents', false),
  ('project-documents', 'project-documents', false),
  ('company-documents', 'company-documents', false),
  ('sops', 'sops', false),
  ('templates', 'templates', false),
  ('knowledge-base', 'knowledge-base', false)
on conflict (id) do update set public = excluded.public;

-- Policy: avatars - employee can access own avatar, admin can access all
drop policy if exists avatars_read on storage.objects;
create policy avatars_read on storage.objects for select to authenticated using (
  bucket_id = 'avatars' and (
    public.is_admin() or
    name = concat(auth.uid(), '/avatar')
  )
);
drop policy if exists avatars_write on storage.objects;
create policy avatars_write on storage.objects for all to authenticated using (
  bucket_id = 'avatars' and (
    public.is_admin() or
    name = concat(auth.uid(), '/avatar')
  )
) with check (
  bucket_id = 'avatars' and (
    public.is_admin() or
    name = concat(auth.uid(), '/avatar')
  )
);

-- Policy: task_attachments - only task members or admin
drop policy if exists task_attachments_read on storage.objects;
create policy task_attachments_read on storage.objects for select to authenticated using (
  bucket_id = 'task-attachments' and exists (
    select 1 from public.task_attachments a
    where a.storage_path = name
      and public.can_access_task(a.task_id)
  )
);
drop policy if exists task_attachments_write on storage.objects;
create policy task_attachments_write on storage.objects for all to authenticated using (
  bucket_id = 'task-attachments' and exists (
    select 1 from public.task_attachments a
    where a.storage_path = name
      and (public.is_admin() or a.uploaded_by = auth.uid())
  )
) with check (
  bucket_id = 'task-attachments' and exists (
    select 1 from public.task_attachments a
    where a.storage_path = name
      and (public.is_admin() or a.uploaded_by = auth.uid())
  )
);

-- Additional bucket policies can be added similarly for other buckets.
-- For brevity, we define a generic policy template that can be reused.

-- Example generic read policy for a bucket that restricts access to related entity
-- (Replace <ENTITY> and <COLUMN> accordingly when adding further policies).

-- create policy if not exists <bucket>_read on storage.objects for select to authenticated using (
--   bucket_id = '<bucket>' and exists (
--     select 1 from public.<entity> e
--     where e.<column> = name
--       and public.can_access_<entity>(e.id)
--   )
-- );

-- Activity events table
create table if not exists storage_events (
  id bigint generated by default as identity primary key,
  type text not null,
  entity_id uuid not null,
  bucket text not null,
  file_path text not null,
  performed_by uuid not null references auth.users(id),
  created_at timestamp with time zone default now()
);

-- Function to log events
create function public.log_storage_event(p_bucket text, p_path text, p_type text, p_entity_id uuid, p_user_id uuid) returns void language plpgsql as $$
begin
  insert into storage_events (type, entity_id, bucket, file_path, performed_by) values (p_type, p_entity_id, p_bucket, p_path, p_user_id);
end;
$$;
